### ISSUE TITLE
Version 4 Broke without specify names in waypoints

### ISSUE THREAD

**Issue by Demolish50** [Archaegeo/Starbase#14]
Having issues with version 4.

If I don't manually specify a name in the waypoint, the z axis always seems to be messed up.  

I've tripled checked the YOLOL to make sure it's all copied correctly.

**Comment by Archaegeo** [comment]
hmm, for now put a wp1 or whatever as the name.  i didnt see it in testing, but thanks for the catch

**Comment by Demolish50** [comment]
Updated with your readme, works ok until you try and use the save button. It will save without a name.
