### ISSUE TITLE
Saving Waypoint does not save any name

### ISSUE THREAD

**Issue by Demolish50** [Archaegeo/Starbase#16]
I'm not sure if you saw my response on your closed ticket. But just a heads up. Adding the waypoint names manually, following your readme works fine. However, when you save a new waypoint it is saved without a name and it does not work unless you manually go to the memory chip and input a name in front of the coords.

**Comment by Bear67** [comment]
If your saving a new waypoint, it Over writes the Entry (Hence over writing the Name as well). But how other are going to by Switching Home locations?

**Comment by Archaegeo** [comment]
This was fixed in last patch.  Now when you save a new location it gives it the name of WP# where # is the waypoint number.  You can then edit the name on the memory chip
