### ISSUE TITLE
Waypoint system

### ISSUE THREAD

**Issue by Dylanwarfare** [Archaegeo/Starbase#17]
I can not figure out why the headings and the buttons for waypoint system buttons to work 

When I stay still headings screen works, but when I move it says error/recalc

Deltas work, isan works

DTW screen works but says WH: ERR Deg
 And WP: ERR Deg

![16310564681671473084307379558062](https://user-images.githubusercontent.com/89859605/132421950-46f07d71-60f6-4981-b41c-fb14dd0564bc.jpg)
![16310564939458130337236549695804](https://user-images.githubusercontent.com/89859605/132421991-bf417f0d-3b2f-4734-8a5d-8bdb9a91ae9a.jpg)

**Comment by Archaegeo** [comment]
Try moving slowing and see if they clear, also try resetting it to line 1 (DTW.yolol)  finally i pushed version 5 today if you want to go through the readme line by line.
