### ISSUE TITLE
MatScanWithMass.yolol - missing instruction step

### ISSUE THREAD

**Issue by BloodyIron** [Archaegeo/Starbase#18]
For this code : https://github.com/Archaegeo/Starbase/blob/main/General%20Stuff/MatScanWithMass.yolol

You forgot to state to change the Scanner "Active" text to "Scanner", so the button doesn't actually turn it on until you rename it on the Material Point Scanner. Might trip up some less savvy gamers ;)

**Comment by Archaegeo** [comment]
Thanks!
