### ISSUE TITLE
30WPIncrement.yolol sticking on line 4

### ISSUE THREAD

**Issue by Urgotopotamus** [Archaegeo/Starbase#20]
Currently having an issue,  just did the step by step of the install, 30WPIncrement.yolol is sticking on line 4,  and will not respond to button inputs.  Cannot scroll through WP's or save them. Set A to 30 as currently setting up to use all 30. confirmed all buttons have power and data, all other panels work.

![Starbase_2021 09 11-12 04](https://user-images.githubusercontent.com/90520435/132954119-696d1476-4c4a-4888-8a82-541c29ed1c2b.png)
![Starbase_2021 09 11-12 04_1](https://user-images.githubusercontent.com/90520435/132954124-2230fd1d-b4f3-4ccc-8a57-e1b23e9f3e0a.png)

**Comment by Admirallj** [comment]
I have the exact same problem...

**Comment by Admirallj** [comment]
Please check your "load"button i had it as WP1 it's supposed to be wpl

**Comment by mikeyroth** [comment]
> Please check your "load"button i had it as WP1 it's supposed to be wpl

Yup  That was my problem.   I had to reset line 4 to goto another line..then it started working correctly

**Comment by AnonymousMonkey75** [comment]
lol same

**Comment by Admirallj** [comment]
Is the "heading" working for you?

**Comment by Urgotopotamus** [comment]
> > Please check your "load"button i had it as WP1 it's supposed to be wpl
> 
> Yup That was my problem. I had to reset line 4 to goto another line..then it started working correctly

This was my issue, on to the next one! Thank you
