### ISSUE TITLE
line 12 in DTW script not working (fix proposal)

### ISSUE THREAD

**Issue by Chrischan1504** [Archaegeo/Starbase#3]
I had a problem at line 12 in the DTW script where instead of going to line 1 or 7, it went to line 13.

I think the cause was that :wpb wasn't available on the network. So line 12 failed and it moved to line 13.

I added wpb to the first memory chip making it available on the network and the script is working now.

**Comment by Archaegeo** [comment]
Wpb is supposed to be defined on warning buttons
