### ISSUE TITLE
Deltas newline coming across as "0"

### ISSUE THREAD

**Issue by the1killer** [Archaegeo/Starbase#5]
Not sure why, i've copied and pasted the code 2 manual times, and 3 or 4 with the VS Code YODK plugin but all results in the same.
Even tried renaming newline variable to different letters.

![image](https://user-images.githubusercontent.com/65697638/129957989-b1926f12-4d50-40ab-9b76-4b9cc4488bdc.png)

**Comment by Archaegeo** [comment]
make it goto line 1, its missing the b="\n"

**Comment by Qwansarium** [comment]
I have the same problem
![image](https://user-images.githubusercontent.com/89095129/129973913-d5fa9e7d-1405-491d-9591-31879f66b8ce.png)

**Comment by Archaegeo** [comment]
Be sure it executes line one

**Comment by Chrischan1504** [comment]
I changed line 9 to: 

:Deltas=s if b!="\n" then goto1 end goto2

**Comment by Archaegeo** [comment]
The issue is often people install the chip on a live chip, so it doesnt start on line 1.  You can put the b="\n" on line 2 as well if you want, but better is to make sure line one executes.
