### ISSUE TITLE
Need for notes

### ISSUE THREAD

**Issue by MrFlackstone** [Archaegeo/Starbase#6]
Hello there,

I've been reading your scripts and first thanks for your work, but im not native english and for me and other people we may need some notes on them to understand what we need to rename or what the script does in game.

Thank you for reading.

**Comment by Archaegeo** [comment]
Im sorry, a lot of the scripts arent ready for notes or are just code snippets i grab to save.   Anything i think is really useful i either comment in the code with // or i make a readme.md for it that shows on its page.
