### ISSUE TITLE
Speed Inaccurate

### ISSUE THREAD

**Issue by HBTurpin** [Archaegeo/Starbase#7]
Not sure if it's any different to original ISAN code but the speed calculation is extremely off. 

I am able to get my ship to show anywhere from 60m/s to 170m/s which is dependent on my heading/pitch whilst only moving in one direction. Should be easy to reproduce.

I'll try and compare this to standard ISAN and update.

**Comment by Archaegeo** [comment]
I have found the speed to be very accurate compared to vanilla V2 ISAN (the ISAN in this github is their beta version, modified to support the heading and pitch system )
