### ISSUE TITLE
names?

### ISSUE THREAD

**Issue by kulwych** [Archaegeo/Starbase#8]
there's nowhere that says what the button and rangefinder should be labeled as.
i take it RFD rangefinderdistance. easy enough to figure out. but then i figure that the button and rangefinder should both be named Approach.  I named them both as such, but any time i try to push the button, it instantly shuts right back off.  Yes buttonstyle is set to 1.

**Comment by Archaegeo** [comment]
the PIP version is meant for range finder to be on different button, you turn it on, get a range on something, then turn on approach.  The other version turns on approach and range at same time.  The PIP version turns off when you range is 0, 1000, or approach button off
